### ISSUE TITLE
Revise ID format to `{package_id}/{type}/{path}`

### ISSUE THREAD

**Issue by rsek** [rsek/datasworn#27]
This should simplify composition and parsing of the IDs, and make it very clear what object type an ID belongs to (as the `type` ID fragment will always be 1:1 with the object's `type` value).

examples:
* `starforged/oracle_collection/core` (currently `starforged/collections/oracles/core`)
* `starforged/asset/companions/glowcat` (currently `starforged/assets/companions/glowcat` -- only changes `assets` to `asset`)

Aside from rewriting the utilities that interact with IDs, some migration utilities should be provided. The simplest (and most portable) way to do this might be a set of regular expressions. Alternatively, they might be written in Haxe to see how well its cross-compilation holds up.

**Comment by rsek** [comment]
## TODO
* [x] update JSON schema generation for IDs, so they get correct `pattern` properties
* [x] create table of regular expressions + replacements that can make the changes.
* [ ] finish #28, so that all the ID breaking changes are bundled together in one release
* [ ] update the IdParser (or possibly rewrite it in Haxe?)
* [ ] package the ID conversion/replacement utilities:
  * `updateMarkdownIdLinks()`
  * `updateId()`
  * a function to make it easier to do all the replacements at once; could just be a reviver that can be plugged into `JSON.parse`
* apply changes to SI data (holding off on this until i know whether this feature will release before, after, or at the same time as SI)

**Comment by rsek** [comment]
current line of thinking: IDs will be restructured to `{type}:${path}`, where `path` is the package ID followed by one or more dictionary keys/indices separated by slashes. examples:

    * `oracle_collection:starforged/core` (currently `starforged/collections/oracle/core`)
    * `asset:starforged/companions/glowcat` (currently `starforged/assets/companions/glowcat`)

this groups all arbitrary path elements together, making globbing much simpler. for example, `oracle_collection:**` can now match all oracles (currently, the same match is `*/collections/oracles/**/*`). it also makes globstars for non-recursive types more attractive, e.g. `asset:**`, so i'll probably implement those.

embedded types will be standardized to `{parentType}.{embeddedType}:${parentPath}.${embeddedPath}`. asset abilities may be folded in to this:

  * `asset.ability:starforged/companions/glowcat.0`
  
 and asset moves an extension of that:
 
  * `asset.ability.move:starforged/companions/glowcat.0.move_name`

**Comment by rsek** [comment]
merged to v0.1.0
