### ISSUE TITLE
Allow more than 3 levels of depth for `RecursiveCollection`

### ISSUE THREAD

**Issue by rsek** [rsek/datasworn#37]
This isn't strictly enforced by the schemas right now, but the ID regular expressions currently allow no more than 3 levels deep. 3 is a somewhat arbitrary choice. I figure it's safer (and easier to accomodate in UX design) if there's a maximum.

Some SI oracles manage to exceed this limit, however. Bumping the limit to 4 would accomodate them. I wouldn't feel awful about pushing that to 5 so there's a little extra headroom, however.

## TODO
* [x] centralize `DEPTH_MAX` as a single constant referenced by schema gen and code gen
* [ ] explore adding some depth limitation to the JSON schema itself (this will require some schema-only intersects that don't really translate to type systems)
* [x] enforce depth limit in post-build validation

**Comment by rsek** [comment]
On the v0.1.0 branch, this has been bumped to 4, for the time being.
